<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke Suite" duration-ms="134778" started-at="2020-10-14T13:34:43Z" finished-at="2020-10-14T13:36:58Z">
    <groups>
    </groups>
    <test name="Smoke Testcases" duration-ms="134778" started-at="2020-10-14T13:34:43Z" finished-at="2020-10-14T13:36:58Z">
      <class name="test.scanario.DemoTest">
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="22980" started-at="2020-10-14T19:04:43Z" finished-at="2020-10-14T19:05:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="SKIP" signature="varifyLoginPageUrl()[pri:1, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPageUrl" duration-ms="2727" started-at="2020-10-14T19:05:07Z" finished-at="2020-10-14T19:05:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.scanario.DemoTest.varifyLoginPageUrl(DemoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPageUrl -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1050" started-at="2020-10-14T19:05:10Z" finished-at="2020-10-14T19:05:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="11508" started-at="2020-10-14T19:05:14Z" finished-at="2020-10-14T19:05:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="SKIP" signature="varifyLoginPageUrl()[pri:1, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPageUrl" duration-ms="58" started-at="2020-10-14T19:05:25Z" finished-at="2020-10-14T19:05:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.scanario.DemoTest.varifyLoginPageUrl(DemoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPageUrl -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1464" started-at="2020-10-14T19:05:25Z" finished-at="2020-10-14T19:05:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="14726" started-at="2020-10-14T19:05:27Z" finished-at="2020-10-14T19:05:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="SKIP" signature="varifyLoginPageUrl()[pri:1, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPageUrl" duration-ms="39" started-at="2020-10-14T19:05:44Z" finished-at="2020-10-14T19:05:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.scanario.DemoTest.varifyLoginPageUrl(DemoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPageUrl -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1200" started-at="2020-10-14T19:05:44Z" finished-at="2020-10-14T19:05:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="12394" started-at="2020-10-14T19:05:46Z" finished-at="2020-10-14T19:05:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="varifyLoginPageUrl()[pri:1, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPageUrl" duration-ms="64" started-at="2020-10-14T19:05:58Z" finished-at="2020-10-14T19:05:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.scanario.DemoTest.varifyLoginPageUrl(DemoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPageUrl -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1393" started-at="2020-10-14T19:05:58Z" finished-at="2020-10-14T19:06:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="13878" started-at="2020-10-14T19:06:00Z" finished-at="2020-10-14T19:06:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="SKIP" signature="varifyLoginPagetitle()[pri:2, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPagetitle" duration-ms="1629" started-at="2020-10-14T19:06:14Z" description="verifying login page title test" finished-at="2020-10-14T19:06:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Mandiri] but found [Mandiri Agen]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Mandiri] but found [Mandiri Agen]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.scanario.DemoTest.varifyLoginPagetitle(DemoTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPagetitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="923" started-at="2020-10-14T19:06:16Z" finished-at="2020-10-14T19:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="12455" started-at="2020-10-14T19:06:17Z" finished-at="2020-10-14T19:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="varifyLoginPagetitle()[pri:2, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPagetitle" duration-ms="253" started-at="2020-10-14T19:06:29Z" description="verifying login page title test" finished-at="2020-10-14T19:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPagetitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1018" started-at="2020-10-14T19:06:29Z" finished-at="2020-10-14T19:06:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="11826" started-at="2020-10-14T19:06:30Z" finished-at="2020-10-14T19:06:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="varifyLoginPageLogo()[pri:3, instance:test.scanario.DemoTest@25b5c5e3]" name="varifyLoginPageLogo" duration-ms="408" started-at="2020-10-14T19:06:42Z" finished-at="2020-10-14T19:06:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyLoginPageLogo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="2165" started-at="2020-10-14T19:06:43Z" finished-at="2020-10-14T19:06:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="setUP" is-config="true" duration-ms="7807" started-at="2020-10-14T19:06:45Z" finished-at="2020-10-14T19:06:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="loginTest()[pri:4, instance:test.scanario.DemoTest@25b5c5e3]" name="loginTest" duration-ms="3894" started-at="2020-10-14T19:06:53Z" finished-at="2020-10-14T19:06:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.scanario.DemoTest@25b5c5e3]" name="tearDown" is-config="true" duration-ms="1228" started-at="2020-10-14T19:06:56Z" finished-at="2020-10-14T19:06:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.scanario.DemoTest -->
    </test> <!-- Smoke Testcases -->
  </suite> <!-- Smoke Suite -->
</testng-results>
